/** Generated by `vite-plugin-forge-web.ts`: the real `@aicad/forge-web` when present, else a stub. */
declare module "virtual:aicad/forge-web" {
  /** Whether `@aicad/forge-web` was found when this bundle was built. */
  export const available: boolean;
  /** Resolved module path, or why it is unavailable. */
  export const source: string;
  /** Dynamically import the module (its shape is checked by the caller). */
  export function load(): Promise<unknown>;
}
