//! Frozen conformance fixtures (interface I9) through the sketch pipeline:
//! - oracle comparison for compound curves: every case of
//!   `corpus/v1/conformance/compound/expansions.json` (generated by an independent Python
//!   implementation) — once with literal fields and once with every numeric field given as an
//!   expression resolved to the same value;
//! - every sketch of `corpus/v1/conformance/invalid/documents.json` that evaluation can decide
//!   without W1's evaluator: the valid documents' sketches evaluate (their solver-level outcome
//!   asserted where the fixture's note states one), and the invalid ones whose codes sketch
//!   evaluation re-checks fail with exactly the fixture's code and path.

mod common;

use common::*;
use forge_core::linalg::Frame;
use forge_ir::v1::metrics::SolveStatus as IrStatus;
use forge_ir::v1::{Feature, LiteralCurve, SketchFeature};
use forge_sketch::{ResolvedValues, SketchError, SketchResult, evaluate_sketch, sketch_expr_sites};
use serde_json::{Value, json};

fn cases() -> Vec<Value> {
    let text =
        std::fs::read_to_string(repo_root().join("corpus/v1/conformance/compound/expansions.json"))
            .expect("fixture");
    // The correctly rounded v1 reader: serde_json's default parser is one ulp off for some
    // 17-digit decimals ([W0-11]), which bit-exact cases would otherwise trip over.
    let v: Value = forge_ir::v1::json::parse(&text).expect("json");
    v["cases"].as_array().expect("cases").clone()
}

/// The sketch with one curve, and the same sketch with every number of the curve replaced by
/// an expression `v<k>` plus the resolved values.
fn sketches(curve: &Value) -> (Value, Value, ResolvedValues) {
    let lit = json!({ "id": "s", "name": "s", "plane": "XY", "curves": [curve] });
    let mut exprs = curve.clone();
    let mut k = 0;
    let mut numbers = Vec::new();
    fn walk(v: &mut Value, k: &mut usize, numbers: &mut Vec<f64>) {
        match v {
            Value::Number(n) => {
                numbers.push(n.as_f64().expect("f64"));
                *v = json!(format!("v{k}"));
                *k += 1;
            }
            Value::Array(a) => a.iter_mut().for_each(|x| walk(x, k, numbers)),
            Value::Object(o) => o.values_mut().for_each(|x| walk(x, k, numbers)),
            _ => {}
        }
    }
    walk(&mut exprs, &mut k, &mut numbers);
    let exp = json!({ "id": "s", "name": "s", "plane": "XY", "curves": [exprs] });
    let s = sketch(exp.clone());
    // Map each `v<k>` to its number through the sites (in document order).
    let sites = sketch_expr_sites(&s);
    let mut values = ResolvedValues::new();
    for site in &sites {
        let k: usize = site.text[1..].parse().expect("v<k>");
        values.insert(site.path.clone(), Ok(numbers[k]));
    }
    assert_eq!(sites.len(), numbers.len(), "every number is a site");
    (lit, exp, values)
}

fn members_of(case: &Value) -> Vec<LiteralCurve> {
    serde_json::from_value(case["members"].clone()).expect("members")
}

fn assert_members(got: &[LiteralCurve], want: &[LiteralCurve], exact: bool, tol: f64, id: &str) {
    assert_eq!(got.len(), want.len(), "{id}: member count");
    for (g, w) in got.iter().zip(want) {
        if exact {
            assert_eq!(g, w, "{id}: bit-exact member");
            continue;
        }
        let pts = |c: &LiteralCurve| -> (String, Vec<[f64; 2]>) {
            match c {
                LiteralCurve::Line { id, start, end, .. } => (id.clone(), vec![*start, *end]),
                LiteralCurve::Arc {
                    id,
                    start,
                    end,
                    center,
                    ..
                } => (id.clone(), vec![*start, *end, *center]),
                other => panic!("{id}: unexpected member {other:?}"),
            }
        };
        let ((gi, gp), (wi, wp)) = (pts(g), pts(w));
        assert_eq!(gi, wi, "{id}");
        for (a, b) in gp.iter().zip(&wp) {
            assert!(
                (a[0] - b[0]).abs() <= tol && (a[1] - b[1]).abs() <= tol,
                "{id}: {a:?} vs {b:?}"
            );
        }
    }
}

#[test]
fn every_compound_fixture_case_matches_through_the_sketch_pipeline() {
    let cases = cases();
    assert!(cases.len() >= 40);
    let mut checked = 0;
    for case in &cases {
        let id = case["id"].as_str().expect("id");
        let (lit, exp, values) = sketches(&case["curve"]);
        for (s, v) in [
            (sketch(lit.clone()), ResolvedValues::new()),
            (sketch(exp.clone()), values.clone()),
        ] {
            let r = evaluate_sketch(&s, &v, &Frame::world());
            if let Some(err) = case.get("error") {
                let e = r.expect_err(id);
                assert_eq!(e.code(), err["code"].as_str().expect("code"), "{id}");
                let field = err["field"].as_str().expect("field");
                assert_eq!(
                    e.path(),
                    Some(format!("/curves/0/{field}").as_str()),
                    "{id}"
                );
                if e.code() != "EXPR_NOT_INTEGER" {
                    assert_eq!(e.details()["field"], json!(field), "{id}");
                }
                assert_error_conforms(&e);
            } else {
                let r = r.unwrap_or_else(|e| panic!("{id}: {e}"));
                let exact = case["exact"].as_bool().expect("exact");
                let tol = case.get("tolerance").and_then(Value::as_f64).unwrap_or(0.0);
                assert_members(&r.trace.solved, &members_of(case), exact, tol, id);
                let construction = case["curve"]
                    .get("construction")
                    .and_then(Value::as_bool)
                    .unwrap_or(false);
                // A closed compound is one region (none when construction).
                assert_eq!(r.regions.len(), usize::from(!construction), "{id}");
            }
            checked += 1;
        }
    }
    assert_eq!(checked, 2 * cases.len());
}

#[test]
fn compound_region_areas_match_the_analytic_areas() {
    use std::f64::consts::PI;
    let area = |curve: Value| {
        let s = sketch(json!({ "id": "s", "name": "s", "plane": "XY", "curves": [curve] }));
        eval(&s).expect("ok").regions[0].area
    };
    let close = |a: f64, b: f64| (a - b).abs() <= 1e-12 * b.abs().max(1.0);
    // rect: w·h − (4 − π)·r².
    let a =
        area(json!({ "kind": "rect", "id": "r", "center": [3, -2], "w": 30, "h": 12, "r": 2.5 }));
    assert!(close(a, 360.0 - (4.0 - PI) * 6.25), "{a}");
    // stadium rect (r = h/2): left/right omitted.
    let a = area(json!({ "kind": "rect", "id": "r", "center": [0, 0], "w": 40, "h": 10, "r": 5 }));
    assert!(close(a, 30.0 * 10.0 + PI * 25.0), "{a}");
    // slot: |b − a|·w + π(w/2)².
    let a = area(json!({ "kind": "slot", "id": "s", "a": [1, 1], "b": [4, 5], "w": 2 }));
    assert!(close(a, 5.0 * 2.0 + PI), "{a}");
    // polygon: ½·n·R²·sin(360°/n).
    let a =
        area(json!({ "kind": "polygon", "id": "p", "center": [0, 0], "n": 8, "circumradius": 5 }));
    assert!(close(a, 0.5 * 8.0 * 25.0 * (2.0 * PI / 8.0).sin()), "{a}");
}

/// Codes of the invalid-documents fixture that sketch evaluation (stage E) re-checks itself,
/// defensively (validation rejects these documents first): evaluating such a sketch must fail
/// with the fixture's code at the fixture's path.
const EVAL_CODES: [&str; 7] = [
    "SKETCH_INVALID_DIMENSION",
    "DEGENERATE_CURVE",
    "INCONSISTENT_ARC",
    "SKETCH_MIXED_MODE",
    "INVALID_COUNT",
    "INVALID_VALUE",
    "UNSUPPORTED_FEATURE_VERSION",
];

/// Evaluate, and when the profile is not a set of loops (the fixture's documents are about
/// validation, e.g. an open arc next to a rectangle), again with every curve as construction
/// geometry: the solve is the same, the region stage is skipped.
fn eval_solver_level(s: &SketchFeature) -> (Result<SketchResult, SketchError>, bool) {
    let r = eval(s);
    match &r {
        Err(e) if REGION_CODES.contains(&e.code()) => (eval(&all_construction(s)), true),
        _ => (r, false),
    }
}

#[test]
fn the_sketches_of_the_invalid_documents_fixture_evaluate_as_the_fixture_states() {
    let text =
        std::fs::read_to_string(repo_root().join("corpus/v1/conformance/invalid/documents.json"))
            .expect("fixture");
    let v: Value = forge_ir::v1::json::parse(&text).expect("json");
    let (mut valid, mut invalid, mut skipped) = (0, 0, 0);
    let mut seen = std::collections::BTreeSet::new();
    for case in v["cases"].as_array().expect("cases") {
        let id = case["id"].as_str().expect("id");
        // `parse_error` cases have no `expected` list.
        let Some(expected) = case.get("expected").and_then(Value::as_array) else {
            continue;
        };
        let Some(parts) = case["document"].get("parts").and_then(Value::as_array) else {
            continue;
        };
        for (pi, part) in parts.iter().enumerate() {
            let Some(features) = part.get("features").and_then(Value::as_array) else {
                continue;
            };
            for (fi, f) in features.iter().enumerate() {
                if f.get("type") != Some(&json!("sketch")) {
                    continue;
                }
                // A structurally invalid sketch never reaches evaluation.
                let Ok(Feature::Sketch(s)) = serde_json::from_value::<Feature>(f.clone()) else {
                    continue;
                };
                if !sketch_expr_sites(&s).is_empty() {
                    skipped += 1; // expression values need W1's evaluator
                    continue;
                }
                let prefix = format!("/parts/{pi}/features/{fi}");
                let mine: Vec<(String, String)> = expected
                    .iter()
                    .filter_map(|e| {
                        let path = e["path"].as_str()?;
                        let rest = path.strip_prefix(&prefix)?;
                        (rest.is_empty() || rest.starts_with('/'))
                            .then(|| (e["code"].as_str().unwrap().to_string(), rest.to_string()))
                    })
                    .collect();
                if expected.is_empty() {
                    let (r, construction) = eval_solver_level(&s);
                    let r = r.unwrap_or_else(|e| panic!("{id}: a valid sketch fails: {e}"));
                    check_valid_case(id, &r, construction);
                    seen.insert(id.to_string());
                    valid += 1;
                } else if !mine.is_empty() && mine.iter().all(|(c, _)| EVAL_CODES.contains(&&**c)) {
                    let e = eval(&s).expect_err(id);
                    let got = (e.code().to_string(), e.path().unwrap_or("").to_string());
                    assert!(mine.contains(&got), "{id}: {got:?} not in {mine:?} ({e})");
                    assert_error_conforms(&e);
                    seen.insert(id.to_string());
                    invalid += 1;
                }
            }
        }
    }
    eprintln!(
        "invalid-documents fixture: {valid} valid sketches evaluated, {invalid} invalid ones fail as expected, {skipped} with expressions skipped"
    );
    for must in [
        "inconsistent-arc-allowed-when-constrained",
        "welded-ends-are-not-a-self-reference",
        "reference-dimension-is-valid",
        "invalid-dimension-value",
        "invalid-dimension-zero-radius",
        "degenerate-arc",
        "inconsistent-arc",
    ] {
        assert!(seen.contains(must), "{must} was not evaluated");
    }
}

/// The solver-level outcome of a valid fixture sketch, where the fixture's note states one.
fn check_valid_case(id: &str, r: &SketchResult, construction: bool) {
    assert_warnings_conform(r);
    match id {
        // [W0-9]: welding makes the coincident between welded ends redundant, not invalid.
        "welded-ends-are-not-a-self-reference" => {
            assert_eq!(
                r.trace.status,
                Some(IrStatus::OverConstrainedRedundant),
                "{id}"
            );
            let d = r.solve_report.as_ref().expect("constrained");
            assert_eq!(d.redundant.len(), 1, "{id}");
            assert_eq!(d.redundant[0].constraint, "k");
            assert!(!d.redundant[0].partial);
            assert!(
                d.redundant[0].implied_by.is_empty(),
                "implied by welding alone"
            );
            let w = r
                .warnings
                .iter()
                .find(|w| w.code == "SKETCH_REDUNDANT_CONSTRAINTS")
                .expect("warning");
            assert_eq!(
                w.details["redundant"],
                json!([{ "constraint": "k", "implied_by": [] }])
            );
        }
        // §4.2: INCONSISTENT_ARC is not checked in constrained mode; the solver's arc rule
        // restores the arc (radius 1 from its start): an open arc, so no region.
        "inconsistent-arc-allowed-when-constrained" => {
            assert!(construction, "{id}: a lone open arc has no region");
            let LiteralCurve::Arc {
                start, end, center, ..
            } = &r.trace.solved[0]
            else {
                panic!("{id}: an arc")
            };
            let d = |p: &[f64; 2]| (p[0] - center[0]).hypot(p[1] - center[1]);
            assert!((d(start) - 1.0).abs() <= 1e-9, "{id}: {}", d(start));
            assert!((d(end) - 1.0).abs() <= 1e-9, "{id}: {}", d(end));
        }
        // A reference angle: reported with no value and its measured 90° (b along +x, r
        // along +y).
        "reference-dimension-is-valid" => {
            assert_eq!(r.trace.dimensions.len(), 1, "{id}");
            let dim = &r.trace.dimensions[0];
            assert_eq!(dim.id, "k");
            assert!(!dim.driving);
            assert_eq!(dim.value, None);
            assert!(
                (dim.measured - 90.0).abs() <= 1e-9,
                "{id}: {}",
                dim.measured
            );
        }
        _ => {}
    }
}
