/**
 * electron-builder configuration (`pnpm --filter @aicad/desktop package[:mac|:win|:linux]`).
 *
 * Layout of a packaged app:
 * - `app.asar`: the main process (`dist/**`) and the built web app (`app-web/`, served from
 *   `app://aicad/`). Inside the asar the web app is covered by the embedded asar integrity check
 *   (`electronFuses` below); as loose files in `resources/` it could be swapped by any process
 *   running as the user.
 * - `resources/bin/aicad[.exe]`: the Forge CLI, with `bin/THIRD_PARTY_LICENSES.txt` (the Rust crates
 *   compiled into it, generated by `scripts/package-notices.mjs` before electron-builder runs).
 * - `resources/LICENSE.txt` (MPL-2.0, which covers aicad) and `resources/THIRD_PARTY_NOTICES.txt`
 *   (the web bundle's notices, also shown in About → Licenses).
 *
 * OPEN: the agent utility process (`dist/agent/worker.js`) has runtime dependencies (@aicad/agent,
 * llm-gateway, forge-web + its .wasm, the agent's prompts/). Packaged builds need them bundled
 * (e.g. an esbuild step for the worker) — see docs/AGENT-IN-APP.md "Open issues". Dev and e2e runs
 * resolve them from the pnpm workspace. That bundle must get the same third-party notices treatment
 * as the web app (packages/app/vite.config.ts).
 * @type {import("electron-builder").Configuration}
 */
module.exports = {
  appId: "dev.aicad.desktop",
  productName: "aicad",
  copyright: "aicad contributors (MPL-2.0)",
  directories: { output: "release", buildResources: "build" },
  files: ["dist/**/*", "package.json", { from: "../app/dist/web", to: "app-web" }],
  extraResources: [
    // Build it first: `cargo build --release -p forge-cli` (optional; without it the app runs compile-only).
    { from: "../../forge/target/release", to: "bin", filter: ["aicad", "aicad.exe"] },
    { from: "build/generated/aicad-THIRD_PARTY_LICENSES.txt", to: "bin/THIRD_PARTY_LICENSES.txt" },
    { from: "../../LICENSE-MPL-2.0", to: "LICENSE.txt" },
    { from: "../app/dist/web/THIRD_PARTY_NOTICES.txt", to: "THIRD_PARTY_NOTICES.txt" },
  ],
  asar: true,
  npmRebuild: false,
  /**
   * Electron fuses (flipped in the binary at package time). Without them any process running as
   * the user can run code as the signed app: `ELECTRON_RUN_AS_NODE`, `NODE_OPTIONS`, or
   * `--inspect` / SIGUSR1 plus a DevTools-protocol client, then e.g. `safeStorage.decryptString`
   * on `agent-keys.json` without a keychain prompt.
   */
  electronFuses: {
    runAsNode: false,
    enableNodeOptionsEnvironmentVariable: false,
    enableNodeCliInspectArguments: false,
    enableEmbeddedAsarIntegrityValidation: true,
    onlyLoadAppFromAsar: true,
    enableCookieEncryption: true,
    grantFileProtocolExtraPrivileges: false,
    loadBrowserProcessSpecificV8Snapshot: false,
  },
  mac: {
    target: [{ target: "dmg", arch: ["arm64", "x64"] }],
    category: "public.app-category.graphics-design",
    hardenedRuntime: true,
    // Explicit, minimal entitlements (JIT only). The default template adds
    // `disable-library-validation`, which lets unsigned dylibs load into the signed app.
    entitlements: "build/entitlements.mac.plist",
    entitlementsInherit: "build/entitlements.mac.plist",
  },
  dmg: { title: "aicad ${version}" },
  win: { target: [{ target: "nsis", arch: ["x64", "arm64"] }] },
  // A per-user install keeps the current no-admin install flow; the app code itself is protected
  // by the asar integrity fuse (Electron >= 30 validates it on Windows too).
  nsis: { oneClick: false, perMachine: false, allowToChangeInstallationDirectory: true },
  linux: { target: [{ target: "AppImage", arch: ["x64", "arm64"] }], category: "Graphics" },
};
