/**
 * electron-builder configuration (`pnpm --filter @aicad/desktop package[:mac|:win|:linux]`). The local Alpha 0 build
 * (PartZero.app, ad-hoc signed, this Mac only) spreads it: electron-builder.alpha-local.cjs.
 *
 * Layout of a packaged app:
 * - `app.asar`: the bundled main process, preload, agent worker (with Forge's WASM and the agent's prompts) and CAD
 *   MCP shim (`bundle/**`, from `scripts/bundle.mjs`: no `node_modules`, every workspace package and SDK inlined),
 *   and the built web app (`app-web/`, served from `app://aicad/`). Inside the asar the code is covered by the
 *   embedded asar integrity check (`electronFuses` below); as loose files in `resources/` it could be swapped by any
 *   process running as the user. The MCP shim alone is unpacked (`asarUnpack`): a CLI agent launches it as a
 *   separate Node process (`ELECTRON_RUN_AS_NODE=1 <app> <shim>`, which needs the runAsNode fuse: only the alpha
 *   config turns it on).
 * - `resources/bin/aicad[.exe]`: the Forge CLI, with `bin/THIRD_PARTY_LICENSES.txt` (the Rust crates
 *   compiled into it, generated by `scripts/package-notices.mjs` before electron-builder runs).
 * - `resources/LICENSE.txt` (MPL-2.0, which covers aicad), `resources/THIRD_PARTY_NOTICES.txt`
 *   (the web bundle's notices, also shown in About → Licenses) and `resources/THIRD_PARTY_NOTICES-desktop.txt`
 *   (the desktop bundle's: `bundle/THIRD_PARTY_NOTICES.txt`).
 * @type {import("electron-builder").Configuration}
 */
const { join } = require("node:path");
const { assertBundleEdition } = require("./scripts/check-bundle-edition.cjs");

module.exports = {
  appId: "dev.aicad.desktop",
  productName: "aicad",
  // `bundle/` must be this config's edition (`bundle.mjs --edition default`, what `pnpm package` makes).
  beforePack: () => assertBundleEdition(join(__dirname, "bundle"), "default"),
  copyright: "aicad contributors (MPL-2.0)",
  directories: { output: "release", buildResources: "build" },
  // The bundle, not `dist/` (tsc output that imports workspace packages at run time): the package has no runtime
  // dependencies, so electron-builder copies no node_modules.
  files: ["bundle/**/*", "package.json", { from: "../app/dist/web", to: "app-web", filter: ["**/*", "!**/*.map"] }],
  extraMetadata: { main: "bundle/main.js" },
  asarUnpack: ["bundle/mcp/**"],
  extraResources: [
    // Build it first: `cargo build --release -p forge-cli` (optional; without it the app runs compile-only).
    { from: "../../forge/target/release", to: "bin", filter: ["aicad", "aicad.exe"] },
    { from: "build/generated/aicad-THIRD_PARTY_LICENSES.txt", to: "bin/THIRD_PARTY_LICENSES.txt" },
    { from: "../../LICENSE-MPL-2.0", to: "LICENSE.txt" },
    { from: "../app/dist/web/THIRD_PARTY_NOTICES.txt", to: "THIRD_PARTY_NOTICES.txt" },
    { from: "bundle/THIRD_PARTY_NOTICES.txt", to: "THIRD_PARTY_NOTICES-desktop.txt" },
  ],
  asar: true,
  npmRebuild: false,
  // ADR 0016 §3: fail the build if a slicer, libslic3r or a slicer's profiles got into the app.
  // A function (not a path string, which electron-builder resolves against the cwd).
  afterPack: require("./scripts/slicer-gate-after-pack.cjs"),
  /**
   * Electron fuses (flipped in the binary at package time). Without them any process running as
   * the user can run code as the signed app: `ELECTRON_RUN_AS_NODE`, `NODE_OPTIONS`, or
   * `--inspect` / SIGUSR1 plus a DevTools-protocol client, then e.g. `safeStorage.decryptString`
   * on `agent-keys.json` without a keychain prompt.
   */
  electronFuses: {
    runAsNode: false,
    enableNodeOptionsEnvironmentVariable: false,
    enableNodeCliInspectArguments: false,
    enableEmbeddedAsarIntegrityValidation: true,
    onlyLoadAppFromAsar: true,
    enableCookieEncryption: true,
    grantFileProtocolExtraPrivileges: false,
    loadBrowserProcessSpecificV8Snapshot: false,
  },
  mac: {
    target: [{ target: "dmg", arch: ["arm64", "x64"] }],
    category: "public.app-category.graphics-design",
    hardenedRuntime: true,
    // Explicit, minimal entitlements (JIT only). The default template adds
    // `disable-library-validation`, which lets unsigned dylibs load into the signed app.
    entitlements: "build/entitlements.mac.plist",
    entitlementsInherit: "build/entitlements.mac.plist",
  },
  dmg: { title: "aicad ${version}" },
  win: { target: [{ target: "nsis", arch: ["x64", "arm64"] }] },
  // A per-user install keeps the current no-admin install flow; the app code itself is protected
  // by the asar integrity fuse (Electron >= 30 validates it on Windows too).
  nsis: { oneClick: false, perMachine: false, allowToChangeInstallationDirectory: true },
  linux: { target: [{ target: "AppImage", arch: ["x64", "arm64"] }], category: "Graphics" },
};
