/**
 * Code generator for @aicad/ir-types.
 *
 * Reads the JSON Schemas that forge-ir derives from its Rust types (serde + schemars) and the
 * normative constants in `forge-ir/src/lib.rs`, and writes TypeScript types + zod schemas to
 * `src/generated/`. Nothing in `src/generated/` is hand-written.
 *
 *   pnpm --filter @aicad/ir-types run generate
 *
 * `test/generated.test.ts` re-runs the generator in memory and fails when the checked-in files
 * are stale. The script is self-contained (Node built-ins only) so that it runs with Node's
 * built-in type stripping, before anything is built.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

/** The subset of JSON Schema (draft 2020-12) that schemars emits for forge-ir. */
export interface JsonSchema {
  $schema?: string;
  $ref?: string;
  $defs?: Record<string, JsonSchema>;
  title?: string;
  description?: string;
  type?: string | string[];
  enum?: unknown[];
  const?: unknown;
  oneOf?: JsonSchema[];
  anyOf?: JsonSchema[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  additionalProperties?: boolean | JsonSchema;
  items?: JsonSchema;
  minItems?: number;
  maxItems?: number;
  minimum?: number;
  format?: string;
  default?: unknown;
}

export interface ModuleOptions {
  /** Repo-relative path of the schema, recorded in the header. */
  source: string;
  /** Exported name of the root (title-level) type. Defaults to the schema title. */
  rootName?: string;
  /** Name of the exported table of schema defaults. */
  defaultsName: string;
  /** Doc comment for the root type when the schema has no description. */
  rootDescription?: string;
}

export interface GeneratedFile {
  /** Path relative to the package root. */
  path: string;
  content: string;
}

const HEADER_NOTE =
  "Code generated by packages/ir-types/scripts/generate.ts. DO NOT EDIT.\n" +
  "Regenerate with `pnpm --filter @aicad/ir-types run generate`.";

interface Rendered {
  ts: string;
  zod: string;
}

interface Decl {
  name: string;
  deps: Set<string>;
  code: string;
}

function pascal(s: string): string {
  return s
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0]!.toUpperCase() + w.slice(1))
    .join("");
}

function refName(ref: string): string {
  const m = /^#\/\$defs\/(.+)$/.exec(ref);
  if (!m) throw new Error(`unsupported $ref ${ref}`);
  return m[1]!;
}

function lit(v: unknown): string {
  return JSON.stringify(v);
}

function jsdoc(lines: string[], indent = ""): string {
  const body = lines.flatMap((l) => l.split("\n")).map((l) => l.replace(/\*\//g, "*\\/"));
  while (body.length > 0 && body[body.length - 1] === "") body.pop();
  if (body.length === 0) return "";
  if (body.length === 1) return `${indent}/** ${body[0]} */\n`;
  return `${indent}/**\n${body.map((l) => (l ? `${indent} * ${l}` : `${indent} *`)).join("\n")}\n${indent} */\n`;
}

function docLines(s: JsonSchema, fallback?: string): string[] {
  const lines: string[] = [];
  if (s.description) lines.push(s.description);
  else if (fallback) lines.push(fallback);
  if (s.default !== undefined) {
    if (lines.length > 0) lines.push("");
    lines.push(`@default ${lit(s.default)}`);
  }
  return lines;
}

function stringConsts(s: JsonSchema): { value: string; description?: string }[] | undefined {
  if (s.enum && s.enum.every((v) => typeof v === "string")) {
    return (s.enum as string[]).map((value) => ({ value }));
  }
  const alts = s.oneOf ?? s.anyOf;
  if (alts && alts.length > 0 && alts.every((a) => typeof a.const === "string")) {
    return alts.map((a) => (a.description ? { value: a.const as string, description: a.description } : { value: a.const as string }));
  }
  return undefined;
}

/** The property that carries a distinct string `const` in every alternative, if any. */
function discriminator(alts: JsonSchema[]): string | undefined {
  const first = alts[0];
  if (!first?.properties) return undefined;
  for (const key of Object.keys(first.properties)) {
    const values = alts.map((a) => a.properties?.[key]?.const);
    if (values.every((v) => typeof v === "string") && new Set(values).size === values.length) return key;
  }
  return undefined;
}

function orderedProps(s: JsonSchema): string[] {
  const props = Object.keys(s.properties ?? {});
  const req = (s.required ?? []).filter((k) => props.includes(k));
  return [...req, ...props.filter((k) => !req.includes(k))];
}

class Generator {
  readonly decls = new Map<string, Decl>();
  readonly defaults = new Map<string, Record<string, unknown>>();
  /** Variant declaration → its discriminated union. */
  readonly variantOf = new Map<string, string>();

  /** Render an inline (anonymous) schema, recording named dependencies. */
  inline(s: JsonSchema, deps: Set<string>, indent: string): Rendered {
    if (s.$ref) {
      const name = refName(s.$ref);
      deps.add(name);
      // Resolved after ordering: a direct reference, or `z.lazy(...)` for a back edge of a cycle.
      return { ts: name, zod: refPlaceholder(name) };
    }
    if (Array.isArray(s.type)) {
      // `type: [T, "null"]`: a field that is nullable on purpose.
      const types = s.type as string[];
      const nonNull = types.filter((t) => t !== "null");
      if (nonNull.length !== 1) throw new Error(`unsupported type list ${lit(types)}`);
      const base = this.inline({ ...s, type: nonNull[0]! }, deps, indent);
      return types.includes("null") ? { ts: `${base.ts} | null`, zod: `${base.zod}.nullable()` } : base;
    }
    const alts = s.anyOf ?? s.oneOf;
    if (alts) {
      const consts = stringConsts(s);
      if (consts) return this.stringUnion(consts.map((c) => c.value));
      const nonNull = alts.filter((a) => a.type !== "null");
      if (nonNull.length === 1 && alts.length === 2) {
        const inner = this.inline(nonNull[0]!, deps, indent);
        return { ts: `${inner.ts} | null`, zod: `${inner.zod}.nullable()` };
      }
      const parts = alts.map((a) => this.inline(a, deps, indent));
      return { ts: parts.map((p) => p.ts).join(" | "), zod: `z.union([${parts.map((p) => p.zod).join(", ")}])` };
    }
    const consts = stringConsts(s);
    if (consts) return this.stringUnion(consts.map((c) => c.value));
    if (s.const !== undefined) return { ts: lit(s.const), zod: `z.literal(${lit(s.const)})` };
    switch (s.type) {
      case "string":
        return { ts: "string", zod: "z.string()" };
      case "boolean":
        return { ts: "boolean", zod: "z.boolean()" };
      case "null":
        return { ts: "null", zod: "z.null()" };
      case "number":
        return { ts: "number", zod: "z.number()" };
      case "integer": {
        let zod = "z.number().int()";
        if (s.minimum !== undefined) zod += `.min(${s.minimum})`;
        if (s.format === "uint32") zod += ".max(4294967295)";
        return { ts: "number", zod };
      }
      case "array": {
        if (!s.items) return { ts: "unknown[]", zod: "z.array(z.unknown())" };
        const item = this.inline(s.items, deps, indent);
        if (s.minItems !== undefined && s.minItems === s.maxItems) {
          const n = s.minItems;
          return {
            ts: `[${Array.from({ length: n }, () => item.ts).join(", ")}]`,
            zod: `z.tuple([${Array.from({ length: n }, () => item.zod).join(", ")}])`,
          };
        }
        const needsParens = item.ts.includes("|");
        let zod = `z.array(${item.zod})`;
        if (s.minItems !== undefined && s.minItems > 0) zod += `.min(${s.minItems})`;
        if (s.maxItems !== undefined) zod += `.max(${s.maxItems})`;
        return { ts: needsParens ? `(${item.ts})[]` : `${item.ts}[]`, zod };
      }
      case "object": {
        if (!s.properties && s.additionalProperties && typeof s.additionalProperties === "object") {
          const v = this.inline(s.additionalProperties, deps, indent);
          return { ts: `{ [key: string]: ${v.ts} }`, zod: `z.record(z.string(), ${v.zod})` };
        }
        if (!s.properties && s.additionalProperties === true) {
          // An open JSON object (e.g. error `details`).
          return { ts: "{ [key: string]: unknown }", zod: "z.record(z.string(), z.unknown())" };
        }
        return this.objectBody(s, deps, indent);
      }
      default:
        return { ts: "unknown", zod: "z.unknown()" };
    }
  }

  stringUnion(values: string[]): Rendered {
    return { ts: values.map(lit).join(" | "), zod: `z.enum([${values.map(lit).join(", ")}])` };
  }

  /** `{ ... }` members for both the TS type and the zod shape. */
  objectBody(s: JsonSchema, deps: Set<string>, indent: string): Rendered {
    const inner = indent + "  ";
    const tsMembers: string[] = [];
    const zodMembers: string[] = [];
    const required = new Set(s.required ?? []);
    for (const key of orderedProps(s)) {
      const prop = s.properties![key]!;
      const r = this.inline(prop, deps, inner);
      const opt = !required.has(key);
      const safeKey = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : lit(key);
      tsMembers.push(`${jsdoc(docLines(prop), inner)}${inner}${safeKey}${opt ? "?" : ""}: ${r.ts};`);
      zodMembers.push(`${inner}${safeKey}: ${r.zod}${opt ? ".exactOptional()" : ""},`);
    }
    const ctor = s.additionalProperties === false ? "z.strictObject" : "z.object";
    return {
      ts: tsMembers.length ? `{\n${tsMembers.join("\n")}\n${indent}}` : "{}",
      zod: zodMembers.length ? `${ctor}({\n${zodMembers.join("\n")}\n${indent}})` : `${ctor}({})`,
    };
  }

  recordDefaults(name: string, s: JsonSchema): void {
    const d: Record<string, unknown> = {};
    for (const key of orderedProps(s)) {
      const prop = s.properties![key]!;
      if (prop.default !== undefined) d[key] = prop.default;
    }
    if (Object.keys(d).length > 0) this.defaults.set(name, d);
  }

  /** Emit a named declaration (type + zod schema). */
  named(name: string, s: JsonSchema, fallbackDoc?: string): void {
    const deps = new Set<string>();
    const doc = jsdoc(docLines(s, fallbackDoc));
    const consts = stringConsts(s);
    let code: string;
    if (consts) {
      const constDocs = consts.filter((c) => c.description);
      const lines = docLines(s);
      if (constDocs.length > 0) {
        if (lines.length > 0) lines.push("");
        for (const c of consts) lines.push(`- ${lit(c.value)}${c.description ? `: ${c.description}` : ""}`);
      }
      const r = this.stringUnion(consts.map((c) => c.value));
      code = `${jsdoc(lines)}export type ${name} = ${r.ts};\n${jsdoc(lines)}export const ${name}Schema = ${r.zod};\n`;
    } else if (s.oneOf && s.oneOf.every((a) => a.type === "object") && discriminator(s.oneOf)) {
      const key = discriminator(s.oneOf)!;
      const variants: string[] = [];
      for (const alt of s.oneOf) {
        const tag = alt.properties![key]!.const as string;
        const vName = `${pascal(tag)}${name}`;
        variants.push(vName);
        this.named(vName, alt, `The \`${key}: ${lit(tag)}\` variant of {@link ${name}}.`);
        this.variantOf.set(vName, name);
        deps.add(vName);
      }
      code =
        `${doc}export type ${name} = ${variants.join(" | ")};\n` +
        `${doc}export const ${name}Schema = z.discriminatedUnion(${lit(key)}, [${variants.map((v) => `${v}Schema`).join(", ")}]);\n`;
    } else if (s.type === "object" && s.properties) {
      const r = this.objectBody(s, deps, "");
      this.recordDefaults(name, s);
      code = `${doc}export interface ${name} ${r.ts}\n${doc}export const ${name}Schema = ${r.zod};\n`;
    } else {
      const r = this.inline(s, deps, "");
      code = `${doc}export type ${name} = ${r.ts};\n${doc}export const ${name}Schema = ${r.zod};\n`;
    }
    this.decls.set(name, { name, deps, code });
  }

  /** Names that lie on a dependency cycle (Tarjan's strongly connected components). */
  cyclic(): Set<string> {
    const index = new Map<string, number>();
    const low = new Map<string, number>();
    const stack: string[] = [];
    const onStack = new Set<string>();
    const out = new Set<string>();
    let next = 0;
    const strong = (v: string): void => {
      index.set(v, next);
      low.set(v, next);
      next++;
      stack.push(v);
      onStack.add(v);
      for (const w of [...this.decls.get(v)!.deps].sort()) {
        if (!index.has(w)) {
          strong(w);
          low.set(v, Math.min(low.get(v)!, low.get(w)!));
        } else if (onStack.has(w)) {
          low.set(v, Math.min(low.get(v)!, index.get(w)!));
        }
      }
      if (low.get(v) === index.get(v)) {
        const scc: string[] = [];
        let w: string;
        do {
          w = stack.pop()!;
          onStack.delete(w);
          scc.push(w);
        } while (w !== v);
        if (scc.length > 1 || this.decls.get(v)!.deps.has(v)) scc.forEach((n) => out.add(n));
      }
    };
    for (const name of [...this.decls.keys()].sort()) if (!index.has(name)) strong(name);
    return out;
  }

  /**
   * Declarations in dependency order (dependencies first, otherwise alphabetical), with
   * references resolved. Acyclic schemas give plain references. On a cycle (the v1 query AST),
   * the DFS back edges become `z.lazy(() => XSchema)` and every lazily referenced schema gets an
   * explicit `z.ZodType<X>` annotation; variants of a discriminated union on a cycle are only
   * reached through their union, so the union's options stay plain object schemas.
   */
  ordered(): Decl[] {
    const out: Decl[] = [];
    const state = new Map<string, "visiting" | "done">();
    const visit = (name: string): void => {
      if (state.has(name)) return;
      state.set(name, "visiting");
      const d = this.decls.get(name);
      if (!d) throw new Error(`missing declaration ${name}`);
      for (const dep of [...d.deps].sort()) visit(dep);
      state.set(name, "done");
      out.push(d);
    };
    const cyclic = this.cyclic();
    for (const name of [...this.decls.keys()].sort()) {
      if (this.variantOf.has(name) && cyclic.has(name)) continue;
      visit(name);
    }
    const pos = new Map(out.map((d, i) => [d.name, i]));
    const lazy = new Set<string>();
    const resolved = out.map((d) => {
      const code = d.code.replace(REF_RE, (_m, target: string) => {
        if (pos.get(target)! < pos.get(d.name)!) return `${target}Schema`;
        lazy.add(target);
        return `z.lazy(() => ${target}Schema)`;
      });
      return { ...d, code };
    });
    for (const target of lazy) {
      if (this.variantOf.has(target)) throw new Error(`variant ${target} cannot be referenced lazily`);
    }
    return resolved.map((d) =>
      lazy.has(d.name)
        ? { ...d, code: d.code.replace(`export const ${d.name}Schema = `, `export const ${d.name}Schema: z.ZodType<${d.name}> = `) }
        : d,
    );
  }
}

const REF_RE = /@@REF:([A-Za-z0-9_]+)@@/g;
function refPlaceholder(name: string): string {
  return `@@REF:${name}@@`;
}

/** Generate one TypeScript module (types + zod schemas) from a JSON Schema document. */
export function generateModule(schema: JsonSchema, opts: ModuleOptions): string {
  const rootName = opts.rootName ?? schema.title;
  if (!rootName) throw new Error("schema has no title; pass rootName");
  const gen = new Generator();
  for (const [name, def] of Object.entries(schema.$defs ?? {})) gen.named(name, def);
  const { $defs: _defs, $schema: _schema, title: _title, ...rootSchema } = schema;
  gen.named(rootName, rootSchema, opts.rootDescription);

  const decls = gen.ordered();
  const out: string[] = [];
  out.push(`// ${HEADER_NOTE.split("\n").join("\n// ")}\n// Source: ${opts.source}\n`);
  out.push(`import { z } from "zod";\n`);
  for (const d of decls) out.push(d.code);

  const defaults = [...gen.defaults.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  const defaultsBody = defaults.length
    ? `{\n${defaults.map(([n, d]) => `  ${n}: ${JSON.stringify(d)},`).join("\n")}\n}`
    : "{}";
  out.push(
    jsdoc([
      "Property defaults declared by the schema (serde `#[serde(default)]`), per type.",
      "Parsing never fills them in: an absent property means \"the default\".",
    ]) + `export const ${opts.defaultsName} = ${defaultsBody} as const;\n`,
  );

  const checks = decls.map((d) => `  AssertTrue<MutuallyAssignable<${d.name}, z.infer<typeof ${d.name}Schema>>>,`);
  out.push(
    "// Compile-time guard: every TS type above is exactly what its zod schema accepts and returns.\n" +
      "type MutuallyAssignable<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;\n" +
      "type AssertTrue<T extends true> = T;\n" +
      `type __SchemaTypeChecks = [\n${checks.join("\n")}\n];\n`,
  );
  return out.join("\n");
}

/** Generate `constants.ts` from the `pub const` items (and their doc comments) in forge-ir's lib.rs. */
export function generateConstants(libRs: string, source: string): string {
  const out: string[] = [`// ${HEADER_NOTE.split("\n").join("\n// ")}\n// Source: ${source}\n`];
  const lines = libRs.split("\n");
  let doc: string[] = [];
  let found = 0;
  for (const line of lines) {
    const docMatch = /^\s*\/\/\/ ?(.*)$/.exec(line);
    if (docMatch) {
      doc.push(docMatch[1]!.replace(/\[`(?:crate::)?([A-Za-z_]+)`\]/g, "`$1`"));
      continue;
    }
    const m = /^pub const ([A-Z_][A-Z0-9_]*): (&str|f64) = (.+);\s*$/.exec(line);
    if (m) {
      const [, name, ty, raw] = m;
      let value: string;
      if (ty === "&str") {
        const str: unknown = JSON.parse(raw!);
        if (typeof str !== "string") throw new Error(`bad string constant ${name}`);
        value = lit(str);
      } else {
        const text = raw!.replace(/_/g, "");
        if (!/^-?\d+(\.\d+)?([eE][+-]?\d+)?$/.test(text) || !Number.isFinite(Number(text))) {
          throw new Error(`bad numeric constant ${name}: ${raw}`);
        }
        value = text;
      }
      out.push(`${jsdoc(doc)}export const ${name} = ${value};\n`);
      found++;
    }
    doc = [];
  }
  if (found === 0) throw new Error("no `pub const` items found in lib.rs");
  return out.join("\n");
}

/**
 * Generate a constants module from a forge-ir constants JSON file (`schema/ir-v1.constants.json`):
 * one `export const KEY = <value> as const;` per top-level key, in file order.
 */
export function generateJsonConstants(json: Record<string, unknown>, source: string, docs: Record<string, string>): string {
  const out: string[] = [`// ${HEADER_NOTE.split("\n").join("\n// ")}\n// Source: ${source}\n`];
  for (const [key, value] of Object.entries(json)) {
    if (!/^[A-Z_][A-Z0-9_]*$/.test(key)) throw new Error(`bad constant name ${key}`);
    const doc = docs[key];
    out.push(`${doc ? jsdoc([doc]) : ""}export const ${key} = ${JSON.stringify(value, null, 2)} as const;\n`);
  }
  return out.join("\n");
}

const V1_CONSTANT_DOCS: Record<string, string> = {
  IR_SCHEMA: "Schema identifier of every v1 IR document.",
  METRICS_SCHEMA: "Schema identifier of every v1 evaluation report.",
  ID_PATTERN: "Every author-chosen id and name matches this pattern (SPEC-v1 §0.3, [W0-12]).",
  MAX_ID_LEN: "Maximum id or name length in bytes.",
  RESERVED_NAMES: "The full v1 reserved-name list (v0 list + CadScript v1 builtins). IR validation applies it to parameter names; feature names are checked against RESERVED_NAMES_V0 ([W0-2]).",
  ERROR_CODES: "The error-code catalogue of SPEC-v1 §7.5: stage (R, E, R/E, W, I), section, detail keys, since.",
  HOLE_SIZES: "The normative standard-hole table of SPEC-v1 §6.5, every value with its sources.",
};

/** Every generated file, computed in memory from the repository sources. */
export function generateAll(repoRoot: string): GeneratedFile[] {
  const schemaDir = "forge/crates/forge-ir/schema";
  const read = (rel: string): string => readFileSync(join(repoRoot, rel), "utf8");
  const ir = JSON.parse(read(`${schemaDir}/ir-v0.schema.json`)) as JsonSchema;
  const metrics = JSON.parse(read(`${schemaDir}/metrics-v0.schema.json`)) as JsonSchema;
  const irV1 = JSON.parse(read(`${schemaDir}/ir-v1.schema.json`)) as JsonSchema;
  const metricsV1 = JSON.parse(read(`${schemaDir}/metrics-v1.schema.json`)) as JsonSchema;
  const constantsV1 = JSON.parse(read(`${schemaDir}/ir-v1.constants.json`)) as Record<string, unknown>;
  const libRs = "forge/crates/forge-ir/src/lib.rs";
  return [
    {
      path: "src/generated/ir-v1.ts",
      content: generateModule(irV1, {
        source: `${schemaDir}/ir-v1.schema.json`,
        rootName: "IrDocument",
        defaultsName: "IR_DEFAULTS",
        rootDescription: "An IR v1 document (`aicad.ir/1`).\nSemantics: forge/crates/forge-ir/SPEC-v1-DRAFT.md.",
      }),
    },
    {
      path: "src/generated/metrics-v1.ts",
      content: generateModule(metricsV1, {
        source: `${schemaDir}/metrics-v1.schema.json`,
        defaultsName: "METRICS_DEFAULTS",
        rootDescription: "An evaluation report (`aicad.metrics/1`); see SPEC-v1-DRAFT.md §7.",
      }),
    },
    {
      path: "src/generated/constants-v1.ts",
      content: generateJsonConstants(constantsV1, `${schemaDir}/ir-v1.constants.json`, V1_CONSTANT_DOCS),
    },
    {
      path: "src/generated/ir-v0.ts",
      content: generateModule(ir, {
        source: `${schemaDir}/ir-v0.schema.json`,
        rootName: "IrDocument",
        defaultsName: "IR_DEFAULTS",
        rootDescription: "An IR document (`aicad.ir/0`): the single source of truth for a design.\nSemantics: forge/crates/forge-ir/SPEC.md.",
      }),
    },
    {
      path: "src/generated/metrics-v0.ts",
      content: generateModule(metrics, {
        source: `${schemaDir}/metrics-v0.schema.json`,
        defaultsName: "METRICS_DEFAULTS",
        rootDescription: "An evaluation report (`aicad.metrics/0`); see SPEC.md §5.",
      }),
    },
    { path: "src/generated/constants.ts", content: generateConstants(read(libRs), libRs) },
  ];
}

export const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const REPO_ROOT = resolve(PACKAGE_ROOT, "../..");

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  for (const file of generateAll(REPO_ROOT)) {
    const target = join(PACKAGE_ROOT, file.path);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, file.content);
    console.log(`wrote ${file.path}`);
  }
}
