/**
 * Real forge-web render meshes (`forge_mesh::tessellate_render`: vertices split per face, each
 * with its face's exact normal), generated by `fixtures/gen-forge-web-meshes.mjs`.
 */
import type { RenderBody } from "../src/engine/types";
import meshes from "./fixtures/forge-web-meshes.json";

interface JsonBody {
  name: string;
  positions: number[];
  normals: number[];
  indices: number[];
  faceRanges: Array<{ face: string; start: number; count: number }>;
  edges: Array<{ edge: string; points: number[] }>;
}

export type ForgeWebFixture = "nema" | "wedge15" | "wedge45";

export function forgeWebBody(key: ForgeWebFixture): RenderBody {
  const b = (meshes as unknown as { bodies: Record<ForgeWebFixture, JsonBody> }).bodies[key];
  return {
    name: b.name,
    positions: Float32Array.from(b.positions),
    normals: Float32Array.from(b.normals),
    indices: Uint32Array.from(b.indices),
    faceRanges: b.faceRanges.map((r) => ({ ...r })),
    edges: b.edges.map((e) => ({ edge: e.edge, points: Float32Array.from(e.points) })),
  };
}

/**
 * The same body as the CLI engine hands it over: one vertex per position shared by every face
 * (as forge-io's OBJ writes `tessellate`'s mesh), normals averaged across the faces.
 */
export function sharedVertexBody(b: RenderBody): RenderBody {
  const key = (i: number): string => `${b.positions[i * 3]},${b.positions[i * 3 + 1]},${b.positions[i * 3 + 2]}`;
  const index = new Map<string, number>();
  const remap: number[] = [];
  const positions: number[] = [];
  const acc: number[] = [];
  for (let i = 0; i < b.positions.length / 3; i++) {
    const k = key(i);
    let j = index.get(k);
    if (j === undefined) {
      j = positions.length / 3;
      index.set(k, j);
      positions.push(b.positions[i * 3]!, b.positions[i * 3 + 1]!, b.positions[i * 3 + 2]!);
      acc.push(0, 0, 0);
    }
    remap.push(j);
    for (let c = 0; c < 3; c++) acc[j * 3 + c]! += b.normals[i * 3 + c]!;
  }
  const normals = new Float32Array(acc.length);
  for (let j = 0; j < acc.length / 3; j++) {
    const l = Math.hypot(acc[j * 3]!, acc[j * 3 + 1]!, acc[j * 3 + 2]!) || 1;
    for (let c = 0; c < 3; c++) normals[j * 3 + c] = acc[j * 3 + c]! / l;
  }
  return { ...b, positions: Float32Array.from(positions), normals, indices: Uint32Array.from(b.indices, (i) => remap[i]!) };
}
