/**
 * The IR v1 domain ops of the command layer: the op catalogue v2 of `@aicad/model-ops`
 * (FULL-MODELING-PLAN §2.2, contract C1), re-exported for the app's modules. The UI, the agent,
 * MCP and (later) the CLI issue the same ops; {@link IrDocStore} applies them as undoable
 * transactions.
 */
export {
  AcceptRefCandidateOp,
  AcceptRefProposalOp,
  AddFeatureOp,
  AddParamOp,
  applyOp,
  candidateReplacesAll,
  CaptureRefOp,
  DeleteFeatureOp,
  DeleteParamOp,
  HOST_ONLY_OPS,
  IrOpSchema,
  MoveFeatureOp,
  OP_CATALOGUE,
  OP_SCHEMAS,
  opInfo,
  opLabel,
  refEntries,
  RenameCurveOp,
  RenameFeatureOp,
  RenameParamOp,
  ReplaceDocumentOp,
  repairOps,
  SetAppearanceOp,
  SetAuthorOp,
  SetFieldOp,
  SetParamOp,
  SetRollbackOp,
  SetSuppressedOp,
  UpdateFeatureOp,
  upgradeConfirmation,
  UpgradeFeatureOp,
  WriteBackSolutionOp,
  type ApplyOptions,
  type HostState,
  type IrOp,
  type IrOpName,
  type OpInfo,
  type OpOrigin,
  type OpOutcome,
  type ParamValueInput,
  type RefLocation,
} from "@aicad/model-ops";
