/** Generated by `vite-plugin-forge-web-sketch.ts`: `@aicad/forge-web/sketch` when built, else a stub. */
declare module "virtual:aicad/forge-web-sketch" {
  /** Whether the sketch WASM was found when this bundle was built. */
  export const available: boolean;
  /** Where it was found, or why not. */
  export const source: string;
  /** The module (`initSketch`, `SketchSession`); rejects when unavailable. */
  export function load(): Promise<unknown>;
}
