/**
 * Provenance names → features. Forge names every generated face `<feature>/<role>:<curve>` (e.g.
 * `plate/cap:end`, `plate/side:bottom`) and every body `<part>/<feature>[#n]`. The feature name is
 * the CadScript `const` name, unique per document, so it maps straight to a timeline row and a
 * source span.
 */
import type { Position, Span } from "@aicad/cadscript";
import type { Feature, IrDocument, PartStudio } from "@aicad/ir-types";
import type { PickResult, RenderBody } from "../engine/types";

/** `plate/cap:end` → `plate`. */
export function featureNameOfFace(face: string): string {
  const slash = face.indexOf("/");
  return slash >= 0 ? face.slice(0, slash) : face;
}

/** `plate/edge:{plate/cap:end|plate/side:top}` → `plate` (the owning feature precedes the `/`). */
export function featureNameOfEdge(edge: string): string {
  return featureNameOfFace(edge);
}

/** `part/pucks#1` → `pucks`. */
export function featureNameOfBody(body: string): string {
  const slash = body.indexOf("/");
  const rest = slash >= 0 ? body.slice(slash + 1) : body;
  const hash = rest.lastIndexOf("#");
  return hash >= 0 && /^\d+$/.test(rest.slice(hash + 1)) ? rest.slice(0, hash) : rest;
}

/** The feature that produced a picked entity: face first, then edge, then body. */
export function featureNameOfPick(p: PickResult): string {
  if (p.face) return featureNameOfFace(p.face);
  if (p.edge) return featureNameOfEdge(p.edge);
  return featureNameOfBody(p.body);
}

export interface FeatureLocation {
  part: PartStudio;
  partIndex: number;
  feature: Feature;
  featureIndex: number;
}

/** Find a feature by id or by name (ids win). */
export function findFeature(ir: IrDocument | null | undefined, idOrName: string): FeatureLocation | null {
  if (!ir) return null;
  let byName: FeatureLocation | null = null;
  for (let pi = 0; pi < ir.parts.length; pi++) {
    const part = ir.parts[pi]!;
    for (let fi = 0; fi < part.features.length; fi++) {
      const feature = part.features[fi]!;
      if (feature.id === idOrName) return { part, partIndex: pi, feature, featureIndex: fi };
      if (!byName && feature.name === idOrName) byName = { part, partIndex: pi, feature, featureIndex: fi };
    }
  }
  return byName;
}

/** Every face (as a pick) generated by a feature, for highlighting it in the viewport. */
export function facesOfFeature(bodies: readonly RenderBody[], featureName: string): PickResult[] {
  const out: PickResult[] = [];
  for (const b of bodies) {
    const seen = new Set<string>();
    for (const r of b.faceRanges) {
      if (featureNameOfFace(r.face) === featureName && !seen.has(r.face)) {
        seen.add(r.face);
        out.push({ body: b.name, face: r.face });
      }
    }
  }
  return out;
}

export function comparePositions(a: Position, b: Position): number {
  return a.line - b.line || a.col - b.col;
}

/** Whether `pos` lies in `span` (end exclusive, but a cursor right after the statement still counts). */
export function spanContains(span: Span, pos: Position): boolean {
  return comparePositions(span.start, pos) <= 0 && comparePositions(pos, span.end) <= 0;
}

/** The feature whose statement contains `pos`, if any. */
export function featureAtPosition(spans: Readonly<Record<string, Span>>, pos: Position): string | null {
  for (const [id, span] of Object.entries(spans)) if (spanContains(span, pos)) return id;
  return null;
}
